# Stage 0, based on Node.js, to build and compile Angular
FROM node:9.8.0-alpine as node

WORKDIR /app
# COPY package.json /app/
COPY ./ /app/
RUN npm install
RUN npm run build --prod 

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.13 as final
COPY --from=node /app/dist/ /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf