version: '3'
services:
  numberword.web:
    image: numberwordweb:prod-v1 
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    environment:
      - NODE_ENV=production
    ports:
      - "4200:80"
    