# Use an official Python runtime as a parent image
FROM node:9.8.0

USER root

ADD . /app

# Set the working directory to /app
WORKDIR /app

EXPOSE 4200

# Install any needed packages
RUN npm install --unsafe-perm @angular/cli -g

# Run 'ng serve' when the container launches
CMD ["ng", "serve", "-H", "0.0.0.0"]