version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8.0-browsers
    steps:
      - checkout
      # ... steps for building/testing app ...
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run frontend test
          command: |
            npm run test-ci 
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # build and push Docker image
      - run:
          name: Build docker image
          command: |
            TAG=web-0.$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker-compose -f docker-compose.prod.yml build 
              docker tag numberwordweb:prod-v1 baron123.azurecr.io/number-word/numberwordweb:$TAG
              docker login baron123.azurecr.io -u $DOCKER_USER -p $DOCKER_PASS        
              docker push baron123.azurecr.io/number-word/numberwordweb
            fi