version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8.0-browsers
    steps:
      - checkout

      - run:
          name: Install gcloud
          command: |
            export CLOUDSDK_CORE_DISABLE_PROMPTS=1
            curl https://sdk.cloud.google.com | bash
            export PATH=${HOME}/google-cloud-sdk/bin:$PATH
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project number-text-convert
            gcloud config set compute/zone australia-southeast1-a
          
      # ... steps for building/testing app ...
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run frontend test
          command: |
            npm run test-ci 
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # build and push Docker image
      - run:
          name: Build docker image
          command: |
            TAG=web-0.$CIRCLE_BUILD_NUM
            export PATH=${HOME}/google-cloud-sdk/bin:$PATH
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              gcloud auth configure-docker
              docker-compose -f docker-compose.prod.yml build 
              docker tag numberwordweb:prod-v1 asia.gcr.io/number-text-convert/numberwordweb:$TAG
              docker push asia.gcr.io/number-text-convert/numberwordweb
            fi