version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.1-ce
    working_directory: .
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      # - run:
      #     name: Install Docker client
      #     command: |
      #       set -x
      #       VER="17.03.0-ce"
      #       curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #       mv /tmp/docker/* /usr/bin

      # build and push Docker image
      # should tag each build, but just need to save some money for storage in registry
      - run: |
          #TAG=0.1.$CIRCLE_BUILD_NUM
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker-compose -f dcoker-compose.prod.yml build #:$TAG .      # (4)
            docker tag numberwordweb:prod-v1 baron123.azurecr.io/number-word/numberwordweb
            docker login baron123.azurecr.io -u $DOCKER_USER -p $DOCKER_PASS         # (5)
            docker push baron123.azurecr.io/number-word/numberwordweb
          fi